# Generated by Django 5.0 on 2023-12-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
