# Generated by Django 5.0 on 2023-12-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsql', '0002_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
    ]
