# Generated by Django 5.0 on 2023-12-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsql', '0003_imageupload_remove_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
